burger=document.querySelector('.burger')
navbar=document.querySelector('.navbar')
navList=document.querySelector('.navList')
rightNav=document.querySelector('.rightNav')
burger.addEventListener('click',()=>
{
navbar.classList.toggle('v-class-resp');
rightNav.classList.toggle('v-class-resp');
navbar.clssList.toogle('h-nav-resp');
})